# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4459121f1c87d20b223b30af7cbe5b8201dea072e9d9862dc9602edaf279995d46eb983c29edf62a2ed99d3a07ef937c808f48630b466889e4c9aa74ae4a53c

test:
  secret_key_base: 22009b367b64f6a570190bfeba3c69259fddba640ef1d7db75e36cea792a1211ed767b18147f617114830a1942f79623859ea1c7c60686323a5f4c18b791052c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
